version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: flask_root_password
      MYSQL_DATABASE: flask_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
